const ShopActionTypes = {
    FETCH_FOODS_START: 'FETCH_FOODS_START',
    FETCH_FOODS_SUCCESS: 'FETCH_FOODS_SUCCESS',
    FETCH_FOODS_FAILURE: 'FETCH_FOODS_FAILURE',
    FETCH_SINGLE_PRODUCT_START: 'FETCH_SINGLE_PRODUCT_START', 
    FETCH_SINGLE_PRODUCT_SUCCESS: 'FETCH_SINGLE_PRODUCT_SUCCESS', 
    FETCH_SINGLE_PRODUCT_FAILURE: 'FETCH_SINGLE_PRODUCT_FAILURE'
}

export default ShopActionTypes;