const PaymentActionTypes = {
    PAYMENT_START: 'PAYMENT_START',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAILURE: 'PAYMENT_FAILURE',
    CLEAR_SUCCESS_MESSAGE: 'CLEAR_SUCCESS_MESSAGE'
}

export default PaymentActionTypes;